language: ruby
cache: bundler
rvm:
- 1.9.3
- 2.0.0
- 2.1.0
- 2.1.1
services:
- mongodb
script: bundle exec rspec
notifications:
  hipchat:
    rooms:
      secure: SQs42VFZ9UgDlGXsINSxKOeusoawJvB1RC5eWskE260H/6OcA/gRNQ0wNYAU5VcVzg1oPKUbyuTKTQySjpkgyPqJFe5kh85OzFAyw7uJ2/p3mJKgvJ+C5YWTIo2Wg4N8Zk4VfTtyyL5OLvqbuMiafVjUJoirVw/Lk/N4FJ9VSGk=
