language: ruby
cache: bundler
rvm:
- 2.1.6
services:
- mongodb
script: bundle exec rspec
deploy:
  provider: rubygems
  api_key:
    secure: "XvDcAbSXTu83v1BIrqakUKIfjUZFHQHTpoSoEeWXzAJ7g+jpbY1hm7yAxyWlMFs/zKS7BuDuQTV8qydcbVqPdrjr9TITkka6U/m85r5AlynlC7pFfAg7Vw7VXs4MLi6eITA/+hLKT49mdZx5NC0Jm4Pv/YtmUAQ8RiUwv8h5DhI="
  gem: trogdir_api_client
  on:
    tags: true
    rvm: 2.1.6
